version = "1.0"
artifacts = [ "/app/output",]

[task]
name = "application/survey-annual-checkup-habits"

[metadata]
difficulty = "easy"
type = "survey"
domain = "healthcare"
tags = [ "annual", "checkup", "habits",]

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 600.0

[environment]
definition = "application/shared-survey-form"
build_timeout_sec = 600.0
cpus = 1
memory_mb = 2048
storage_mb = 10240
gpus = 0
