version = "1.0"
artifacts = [ "/app/output",]

[task]
name = "application/note-to-csv"

[metadata]
difficulty = "easy"
type = "os-app"
os = "linux"
domain = "software"
tags = [ "file transform", "csv creation", "desktop editor", "structured output",]


[verifier]
timeout_sec = 300.0

[agent]
timeout_sec = 1800.0

[environment]
definition = "application/shared-os-app-linux"
build_timeout_sec = 1200.0
cpus = 2
memory_mb = 4096
storage_mb = 8192
gpus = 0
