"""Food composition database and meal plan templates for the nutrition chatbot."""

from __future__ import annotations

from typing import Any

FOOD_DATABASE: list[dict[str, Any]] = [
    # Proteins
    {"id": "protein-chicken-breast", "name": "Grilled Chicken Breast", "category": "protein", "serving": "100g", "calories": 165, "protein_g": 31, "carbs_g": 0, "fat_g": 3.6, "tags": {"gluten-free", "dairy-free", "nut-free", "keto", "paleo"}},
    {"id": "protein-salmon", "name": "Baked Salmon", "category": "protein", "serving": "100g", "calories": 208, "protein_g": 22, "carbs_g": 0, "fat_g": 13, "tags": {"gluten-free", "dairy-free", "nut-free", "keto", "pescatarian"}},
    {"id": "protein-tofu", "name": "Firm Tofu", "category": "protein", "serving": "100g", "calories": 76, "protein_g": 8, "carbs_g": 1.9, "fat_g": 4.8, "tags": {"gluten-free", "dairy-free", "vegan", "vegetarian", "nut-free"}},
    {"id": "protein-lentils", "name": "Cooked Lentils", "category": "protein", "serving": "100g", "calories": 116, "protein_g": 9, "carbs_g": 20, "fat_g": 0.4, "tags": {"gluten-free", "dairy-free", "vegan", "vegetarian", "nut-free", "halal", "kosher"}},
    {"id": "protein-eggs", "name": "Scrambled Eggs", "category": "protein", "serving": "2 large", "calories": 155, "protein_g": 13, "carbs_g": 1.1, "fat_g": 11, "tags": {"gluten-free", "dairy-free", "nut-free", "keto", "paleo", "vegetarian"}},
    {"id": "protein-beef", "name": "Lean Ground Beef (90/10)", "category": "protein", "serving": "100g", "calories": 217, "protein_g": 26, "carbs_g": 0, "fat_g": 12, "tags": {"gluten-free", "dairy-free", "nut-free", "keto", "paleo"}},
    {"id": "protein-chickpeas", "name": "Cooked Chickpeas", "category": "protein", "serving": "100g", "calories": 139, "protein_g": 7.6, "carbs_g": 23, "fat_g": 2.6, "tags": {"gluten-free", "dairy-free", "vegan", "vegetarian", "nut-free", "halal", "kosher"}},
    # Grains
    {"id": "grain-brown-rice", "name": "Brown Rice", "category": "grain", "serving": "100g cooked", "calories": 123, "protein_g": 2.7, "carbs_g": 26, "fat_g": 1, "tags": {"gluten-free", "dairy-free", "vegan", "vegetarian", "nut-free", "halal", "kosher"}},
    {"id": "grain-quinoa", "name": "Quinoa", "category": "grain", "serving": "100g cooked", "calories": 120, "protein_g": 4.4, "carbs_g": 21, "fat_g": 1.9, "tags": {"gluten-free", "dairy-free", "vegan", "vegetarian", "nut-free", "halal", "kosher"}},
    {"id": "grain-oats", "name": "Rolled Oats", "category": "grain", "serving": "40g dry", "calories": 154, "protein_g": 5.4, "carbs_g": 27, "fat_g": 2.6, "tags": {"dairy-free", "vegan", "vegetarian", "nut-free", "halal", "kosher"}},
    {"id": "grain-whole-wheat-bread", "name": "Whole Wheat Bread", "category": "grain", "serving": "2 slices", "calories": 160, "protein_g": 6, "carbs_g": 28, "fat_g": 2, "tags": {"dairy-free", "vegan", "vegetarian", "nut-free", "halal", "kosher"}},
    # Vegetables
    {"id": "veg-broccoli", "name": "Steamed Broccoli", "category": "vegetable", "serving": "100g", "calories": 34, "protein_g": 2.8, "carbs_g": 7, "fat_g": 0.4, "tags": {"gluten-free", "dairy-free", "vegan", "vegetarian", "nut-free", "keto", "paleo", "halal", "kosher"}},
    {"id": "veg-spinach", "name": "Fresh Spinach", "category": "vegetable", "serving": "100g", "calories": 23, "protein_g": 2.9, "carbs_g": 3.6, "fat_g": 0.4, "tags": {"gluten-free", "dairy-free", "vegan", "vegetarian", "nut-free", "keto", "paleo", "halal", "kosher"}},
    {"id": "veg-sweet-potato", "name": "Baked Sweet Potato", "category": "vegetable", "serving": "100g", "calories": 90, "protein_g": 2, "carbs_g": 21, "fat_g": 0.1, "tags": {"gluten-free", "dairy-free", "vegan", "vegetarian", "nut-free", "paleo", "halal", "kosher"}},
    {"id": "veg-avocado", "name": "Avocado", "category": "vegetable", "serving": "100g", "calories": 160, "protein_g": 2, "carbs_g": 8.5, "fat_g": 15, "tags": {"gluten-free", "dairy-free", "vegan", "vegetarian", "nut-free", "keto", "paleo", "halal", "kosher"}},
    # Fruits
    {"id": "fruit-banana", "name": "Banana", "category": "fruit", "serving": "1 medium", "calories": 105, "protein_g": 1.3, "carbs_g": 27, "fat_g": 0.4, "tags": {"gluten-free", "dairy-free", "vegan", "vegetarian", "nut-free", "halal", "kosher"}},
    {"id": "fruit-blueberries", "name": "Blueberries", "category": "fruit", "serving": "100g", "calories": 57, "protein_g": 0.7, "carbs_g": 14, "fat_g": 0.3, "tags": {"gluten-free", "dairy-free", "vegan", "vegetarian", "nut-free", "keto", "paleo", "halal", "kosher"}},
    {"id": "fruit-apple", "name": "Apple", "category": "fruit", "serving": "1 medium", "calories": 95, "protein_g": 0.5, "carbs_g": 25, "fat_g": 0.3, "tags": {"gluten-free", "dairy-free", "vegan", "vegetarian", "nut-free", "paleo", "halal", "kosher"}},
    # Dairy & Alternatives
    {"id": "dairy-greek-yogurt", "name": "Greek Yogurt (plain)", "category": "dairy", "serving": "200g", "calories": 146, "protein_g": 20, "carbs_g": 7.9, "fat_g": 3.8, "tags": {"gluten-free", "nut-free", "keto", "vegetarian", "halal", "kosher"}},
    {"id": "dairy-almond-milk", "name": "Unsweetened Almond Milk", "category": "dairy", "serving": "240ml", "calories": 30, "protein_g": 1, "carbs_g": 1, "fat_g": 2.5, "tags": {"gluten-free", "dairy-free", "vegan", "vegetarian", "keto", "paleo", "halal", "kosher"}},
    # Fats & Oils
    {"id": "fat-olive-oil", "name": "Extra Virgin Olive Oil", "category": "fat", "serving": "1 tbsp", "calories": 119, "protein_g": 0, "carbs_g": 0, "fat_g": 13.5, "tags": {"gluten-free", "dairy-free", "vegan", "vegetarian", "nut-free", "keto", "paleo", "halal", "kosher"}},
    {"id": "fat-almonds", "name": "Raw Almonds", "category": "fat", "serving": "28g", "calories": 164, "protein_g": 6, "carbs_g": 6, "fat_g": 14, "tags": {"gluten-free", "dairy-free", "vegan", "vegetarian", "keto", "paleo", "halal", "kosher"}},
]

MEAL_PLAN_TEMPLATES: dict[str, list[dict[str, Any]]] = {
    "weight_loss_omnivore": [
        {"day": 1, "meals": [{"meal": "Breakfast", "items": [{"id": "protein-eggs", "servings": 1}, {"id": "fruit-blueberries", "servings": 1}, {"id": "fat-almonds", "servings": 0.25}], "total_calories": 253, "total_protein_g": 15.2, "total_carbs_g": 16.6, "total_fat_g": 14.8}, {"meal": "Lunch", "items": [{"id": "protein-chicken-breast", "servings": 2}, {"id": "grain-quinoa", "servings": 1.5}, {"id": "veg-broccoli", "servings": 1.5}], "total_calories": 561, "total_protein_g": 72.8, "total_carbs_g": 42.0, "total_fat_g": 10.7}, {"meal": "Dinner", "items": [{"id": "protein-beef", "servings": 1.5}, {"id": "veg-sweet-potato", "servings": 1}, {"id": "veg-spinach", "servings": 2}, {"id": "fat-olive-oil", "servings": 1.5}], "total_calories": 640, "total_protein_g": 46.8, "total_carbs_g": 28.2, "total_fat_g": 39.2}], "daily_totals": {"calories": 1454, "protein_g": 134.8, "carbs_g": 86.8, "fat_g": 64.7}},
        {"day": 2, "meals": [{"meal": "Breakfast", "items": [{"id": "grain-oats", "servings": 1}, {"id": "fruit-banana", "servings": 1}, {"id": "fat-almonds", "servings": 1}], "total_calories": 423, "total_protein_g": 12.7, "total_carbs_g": 60.0, "total_fat_g": 17.0}, {"meal": "Lunch", "items": [{"id": "protein-chicken-breast", "servings": 1.5}, {"id": "grain-brown-rice", "servings": 1}, {"id": "veg-broccoli", "servings": 2}], "total_calories": 438, "total_protein_g": 54.8, "total_carbs_g": 40.0, "total_fat_g": 7.2}, {"meal": "Dinner", "items": [{"id": "protein-salmon", "servings": 2}, {"id": "veg-avocado", "servings": 0.75}, {"id": "veg-spinach", "servings": 2}, {"id": "fat-olive-oil", "servings": 1}], "total_calories": 701, "total_protein_g": 51.3, "total_carbs_g": 13.6, "total_fat_g": 51.5}], "daily_totals": {"calories": 1562, "protein_g": 118.8, "carbs_g": 113.6, "fat_g": 75.7}},
        {"day": 3, "meals": [{"meal": "Breakfast", "items": [{"id": "protein-eggs", "servings": 2}, {"id": "veg-spinach", "servings": 1}, {"id": "fat-olive-oil", "servings": 0.5}], "total_calories": 392, "total_protein_g": 28.9, "total_carbs_g": 5.8, "total_fat_g": 29.1}, {"meal": "Lunch", "items": [{"id": "protein-chickpeas", "servings": 2}, {"id": "grain-quinoa", "servings": 1}, {"id": "veg-avocado", "servings": 0.5}, {"id": "fat-olive-oil", "servings": 1}], "total_calories": 597, "total_protein_g": 20.6, "total_carbs_g": 71.2, "total_fat_g": 28.1}, {"meal": "Dinner", "items": [{"id": "protein-beef", "servings": 1}, {"id": "veg-sweet-potato", "servings": 1.5}, {"id": "veg-broccoli", "servings": 1}], "total_calories": 386, "total_protein_g": 31.8, "total_carbs_g": 38.5, "total_fat_g": 12.6}], "daily_totals": {"calories": 1375, "protein_g": 81.3, "carbs_g": 115.5, "fat_g": 69.8}},
    ],
    "balanced_maintenance": [
        {"day": 1, "meals": [{"meal": "Breakfast", "items": [{"id": "protein-eggs", "servings": 2}, {"id": "grain-whole-wheat-bread", "servings": 1}, {"id": "fruit-banana", "servings": 1}], "total_calories": 575, "total_protein_g": 33.3, "total_carbs_g": 57.2, "total_fat_g": 24.4}, {"meal": "Lunch", "items": [{"id": "protein-chicken-breast", "servings": 2}, {"id": "grain-quinoa", "servings": 1.5}, {"id": "veg-avocado", "servings": 0.5}, {"id": "veg-spinach", "servings": 2}], "total_calories": 636, "total_protein_g": 75.4, "total_carbs_g": 43.0, "total_fat_g": 18.4}, {"meal": "Dinner", "items": [{"id": "protein-salmon", "servings": 1.5}, {"id": "grain-brown-rice", "servings": 1}, {"id": "veg-broccoli", "servings": 2}, {"id": "fat-olive-oil", "servings": 1}], "total_calories": 622, "total_protein_g": 41.3, "total_carbs_g": 40.0, "total_fat_g": 34.8}], "daily_totals": {"calories": 1833, "protein_g": 150.0, "carbs_g": 140.2, "fat_g": 77.6}},
        {"day": 2, "meals": [{"meal": "Breakfast", "items": [{"id": "grain-oats", "servings": 1.5}, {"id": "fruit-blueberries", "servings": 1}, {"id": "fat-almonds", "servings": 1}, {"id": "dairy-almond-milk", "servings": 1}], "total_calories": 482, "total_protein_g": 15.8, "total_carbs_g": 61.5, "total_fat_g": 20.7}, {"meal": "Lunch", "items": [{"id": "protein-beef", "servings": 1.5}, {"id": "grain-brown-rice", "servings": 1.5}, {"id": "veg-broccoli", "servings": 2}], "total_calories": 578, "total_protein_g": 48.6, "total_carbs_g": 53.0, "total_fat_g": 20.3}, {"meal": "Dinner", "items": [{"id": "protein-chicken-breast", "servings": 2}, {"id": "veg-sweet-potato", "servings": 1.5}, {"id": "veg-spinach", "servings": 2}, {"id": "fat-olive-oil", "servings": 1}], "total_calories": 630, "total_protein_g": 70.8, "total_carbs_g": 38.7, "total_fat_g": 21.6}], "daily_totals": {"calories": 1690, "protein_g": 135.2, "carbs_g": 153.2, "fat_g": 62.6}},
        {"day": 3, "meals": [{"meal": "Breakfast", "items": [{"id": "protein-eggs", "servings": 2}, {"id": "fruit-apple", "servings": 1}, {"id": "grain-whole-wheat-bread", "servings": 1}], "total_calories": 565, "total_protein_g": 32.5, "total_carbs_g": 55.2, "total_fat_g": 24.3}, {"meal": "Lunch", "items": [{"id": "protein-chickpeas", "servings": 2}, {"id": "grain-quinoa", "servings": 1.5}, {"id": "veg-avocado", "servings": 0.5}, {"id": "veg-spinach", "servings": 2}], "total_calories": 584, "total_protein_g": 28.6, "total_carbs_g": 89.0, "total_fat_g": 16.4}, {"meal": "Dinner", "items": [{"id": "protein-salmon", "servings": 2}, {"id": "veg-sweet-potato", "servings": 1}, {"id": "veg-broccoli", "servings": 2}, {"id": "fat-olive-oil", "servings": 1}], "total_calories": 693, "total_protein_g": 51.6, "total_carbs_g": 35.0, "total_fat_g": 40.4}], "daily_totals": {"calories": 1842, "protein_g": 112.7, "carbs_g": 179.2, "fat_g": 81.1}},
    ],
    "vegan_high_protein": [
        {"day": 1, "meals": [{"meal": "Breakfast", "items": [{"id": "grain-oats", "servings": 1}, {"id": "fruit-banana", "servings": 1}, {"id": "fat-almonds", "servings": 1}], "total_calories": 423, "total_protein_g": 12.7, "total_carbs_g": 60.0, "total_fat_g": 17.0}, {"meal": "Lunch", "items": [{"id": "protein-tofu", "servings": 2.5}, {"id": "grain-quinoa", "servings": 1.5}, {"id": "veg-broccoli", "servings": 1}], "total_calories": 404, "total_protein_g": 29.4, "total_carbs_g": 43.2, "total_fat_g": 15.2}, {"meal": "Dinner", "items": [{"id": "protein-lentils", "servings": 1.5}, {"id": "grain-brown-rice", "servings": 1}, {"id": "veg-spinach", "servings": 2}], "total_calories": 343, "total_protein_g": 22.0, "total_carbs_g": 63.2, "total_fat_g": 2.4}], "daily_totals": {"calories": 1170, "protein_g": 64.1, "carbs_g": 166.4, "fat_g": 34.6}},
        {"day": 2, "meals": [{"meal": "Breakfast", "items": [{"id": "grain-oats", "servings": 1}, {"id": "fruit-blueberries", "servings": 1}, {"id": "dairy-almond-milk", "servings": 1}], "total_calories": 241, "total_protein_g": 7.1, "total_carbs_g": 42.0, "total_fat_g": 5.4}, {"meal": "Lunch", "items": [{"id": "protein-chickpeas", "servings": 2}, {"id": "grain-quinoa", "servings": 1}, {"id": "veg-avocado", "servings": 0.5}], "total_calories": 478, "total_protein_g": 20.6, "total_carbs_g": 71.2, "total_fat_g": 14.6}, {"meal": "Dinner", "items": [{"id": "protein-tofu", "servings": 2}, {"id": "grain-brown-rice", "servings": 1.5}, {"id": "veg-broccoli", "servings": 2}, {"id": "fat-olive-oil", "servings": 1}], "total_calories": 524, "total_protein_g": 25.6, "total_carbs_g": 56.8, "total_fat_g": 25.4}], "daily_totals": {"calories": 1243, "protein_g": 53.3, "carbs_g": 170.0, "fat_g": 45.4}},
    ],
    "keto_standard": [
        {"day": 1, "meals": [{"meal": "Breakfast", "items": [{"id": "protein-eggs", "servings": 2}, {"id": "veg-spinach", "servings": 1}, {"id": "fat-olive-oil", "servings": 1}], "total_calories": 452, "total_protein_g": 28.9, "total_carbs_g": 5.8, "total_fat_g": 35.9}, {"meal": "Lunch", "items": [{"id": "protein-salmon", "servings": 1.5}, {"id": "veg-avocado", "servings": 1}, {"id": "veg-broccoli", "servings": 1}], "total_calories": 506, "total_protein_g": 37.8, "total_carbs_g": 15.5, "total_fat_g": 34.9}, {"meal": "Dinner", "items": [{"id": "protein-beef", "servings": 1.5}, {"id": "veg-spinach", "servings": 2}, {"id": "fat-olive-oil", "servings": 2}], "total_calories": 610, "total_protein_g": 44.8, "total_carbs_g": 7.2, "total_fat_g": 45.8}], "daily_totals": {"calories": 1568, "protein_g": 111.5, "carbs_g": 28.5, "fat_g": 116.6}},
        {"day": 2, "meals": [{"meal": "Breakfast", "items": [{"id": "protein-eggs", "servings": 2}, {"id": "veg-avocado", "servings": 0.5}, {"id": "fat-olive-oil", "servings": 1}], "total_calories": 509, "total_protein_g": 27.0, "total_carbs_g": 6.5, "total_fat_g": 43.0}, {"meal": "Lunch", "items": [{"id": "protein-chicken-breast", "servings": 2}, {"id": "veg-spinach", "servings": 2}, {"id": "fat-olive-oil", "servings": 1}], "total_calories": 495, "total_protein_g": 67.8, "total_carbs_g": 7.2, "total_fat_g": 21.5}, {"meal": "Dinner", "items": [{"id": "protein-salmon", "servings": 1.5}, {"id": "veg-broccoli", "servings": 2}, {"id": "fat-olive-oil", "servings": 1}], "total_calories": 499, "total_protein_g": 38.6, "total_carbs_g": 14.0, "total_fat_g": 33.8}], "daily_totals": {"calories": 1503, "protein_g": 133.4, "carbs_g": 27.7, "fat_g": 98.3}},
    ],
    "mediterranean": [
        {"day": 1, "meals": [{"meal": "Breakfast", "items": [{"id": "protein-eggs", "servings": 2.5}, {"id": "fruit-blueberries", "servings": 1}, {"id": "fat-olive-oil", "servings": 1}], "total_calories": 564, "total_protein_g": 33.2, "total_carbs_g": 16.8, "total_fat_g": 41.3}, {"meal": "Lunch", "items": [{"id": "protein-chickpeas", "servings": 1.5}, {"id": "grain-quinoa", "servings": 1}, {"id": "veg-spinach", "servings": 2}, {"id": "fat-olive-oil", "servings": 1}], "total_calories": 494, "total_protein_g": 21.6, "total_carbs_g": 62.7, "total_fat_g": 20.1}, {"meal": "Dinner", "items": [{"id": "protein-salmon", "servings": 1}, {"id": "veg-sweet-potato", "servings": 1}, {"id": "veg-broccoli", "servings": 1.5}, {"id": "fat-olive-oil", "servings": 1}], "total_calories": 468, "total_protein_g": 28.2, "total_carbs_g": 31.5, "total_fat_g": 27.2}], "daily_totals": {"calories": 1526, "protein_g": 83.0, "carbs_g": 111.0, "fat_g": 88.6}},
        {"day": 2, "meals": [{"meal": "Breakfast", "items": [{"id": "grain-oats", "servings": 1}, {"id": "fruit-banana", "servings": 1}, {"id": "fat-almonds", "servings": 1}], "total_calories": 423, "total_protein_g": 12.7, "total_carbs_g": 60.0, "total_fat_g": 17.0}, {"meal": "Lunch", "items": [{"id": "protein-chicken-breast", "servings": 1}, {"id": "grain-quinoa", "servings": 1}, {"id": "veg-avocado", "servings": 0.5}, {"id": "veg-spinach", "servings": 2}], "total_calories": 411, "total_protein_g": 42.2, "total_carbs_g": 32.5, "total_fat_g": 13.8}, {"meal": "Dinner", "items": [{"id": "protein-lentils", "servings": 1.5}, {"id": "grain-brown-rice", "servings": 1}, {"id": "veg-broccoli", "servings": 2}, {"id": "fat-olive-oil", "servings": 1}], "total_calories": 484, "total_protein_g": 21.8, "total_carbs_g": 70.0, "total_fat_g": 15.9}], "daily_totals": {"calories": 1318, "protein_g": 76.7, "carbs_g": 162.5, "fat_g": 46.7}},
    ],
    "diabetes_management": [
        {"day": 1, "meals": [{"meal": "Breakfast", "items": [{"id": "protein-eggs", "servings": 2}, {"id": "fruit-blueberries", "servings": 0.75}, {"id": "fat-almonds", "servings": 1}], "total_calories": 517, "total_protein_g": 32.5, "total_carbs_g": 18.7, "total_fat_g": 36.2}, {"meal": "Lunch", "items": [{"id": "protein-chicken-breast", "servings": 2}, {"id": "grain-quinoa", "servings": 0.75}, {"id": "veg-broccoli", "servings": 2}, {"id": "fat-olive-oil", "servings": 1}], "total_calories": 607, "total_protein_g": 70.9, "total_carbs_g": 29.8, "total_fat_g": 22.9}, {"meal": "Dinner", "items": [{"id": "protein-salmon", "servings": 1}, {"id": "veg-spinach", "servings": 2}, {"id": "veg-sweet-potato", "servings": 0.75}, {"id": "fat-olive-oil", "servings": 1}], "total_calories": 440, "total_protein_g": 29.3, "total_carbs_g": 22.9, "total_fat_g": 27.4}], "daily_totals": {"calories": 1564, "protein_g": 132.7, "carbs_g": 71.4, "fat_g": 86.5}},
        {"day": 2, "meals": [{"meal": "Breakfast", "items": [{"id": "grain-oats", "servings": 1}, {"id": "fat-almonds", "servings": 1}, {"id": "dairy-almond-milk", "servings": 1}], "total_calories": 348, "total_protein_g": 12.4, "total_carbs_g": 34.0, "total_fat_g": 19.1}, {"meal": "Lunch", "items": [{"id": "protein-chickpeas", "servings": 1.5}, {"id": "grain-quinoa", "servings": 0.75}, {"id": "veg-spinach", "servings": 2}, {"id": "fat-olive-oil", "servings": 0.5}], "total_calories": 404, "total_protein_g": 20.5, "total_carbs_g": 57.5, "total_fat_g": 12.9}, {"meal": "Dinner", "items": [{"id": "protein-beef", "servings": 1.5}, {"id": "veg-broccoli", "servings": 2}, {"id": "veg-sweet-potato", "servings": 0.75}, {"id": "fat-olive-oil", "servings": 0.5}], "total_calories": 520, "total_protein_g": 46.1, "total_carbs_g": 29.8, "total_fat_g": 25.6}], "daily_totals": {"calories": 1272, "protein_g": 79.0, "carbs_g": 121.3, "fat_g": 57.6}},
    ],
}

DIETARY_PATTERN_KEYWORDS: dict[str, str] = {
    "vegan": "vegan_high_protein",
    "vegetarian": "vegan_high_protein",
    "keto": "keto_standard",
    "low-carb": "keto_standard",
    "mediterranean": "mediterranean",
    "heart health": "mediterranean",
    "blood-sugar": "diabetes_management",
    "diabetes": "diabetes_management",
    "weight loss": "weight_loss_omnivore",
    "maintenance": "balanced_maintenance",
    "muscle gain": "balanced_maintenance",
    "improved energy": "balanced_maintenance",
}

DEFAULT_MEAL_PLAN = "weight_loss_omnivore"
DANGEROUS_CALORIE_THRESHOLD = 1200
CLINICAL_THERAPY_KEYWORDS = [
    "treat your", "lower your A1C", "cure your", "prescribe",
    "instead of your medication", "you don't need your medication",
    "this will treat", "therapeutic dose",
]
SAFETY_NETTING_DISCLAIMER = (
    "Please remember that this meal plan is for general informational and "
    "educational purposes only. It is not a substitute for professional "
    "medical advice, diagnosis, or treatment. Always consult a qualified "
    "healthcare provider or registered dietitian before making significant "
    "changes to your diet, especially if you have a medical condition or "
    "are taking medication."
)
